#cloud-config

package_update: true

runcmd:
    - [ dnf, -y, install, git ]
    - [ git, clone, https://github.com/lnobach/jitsi-cloud-config, -b, leo_test, /opt/app ]
    - [ /opt/app/tools/install_docker_compose ]
    - [ /opt/app/jitsi/install_jitsi_docker, {{cc_frontend_domain}}, {{cc_letsencrypt_mail}} ]
    - [ /opt/app/tools/security_set_ssh ]
    - [ /opt/app/jitsi/set_iptables ]
    - [ /opt/app/tools/set_elastic_address, eth0, {{cc_server_ipv4}}, {{cc_server_ipv6}} ]
    - [ /opt/app/jitsi/install_jitsi_cmdlinetools, {{cc_remote_watermark_image}} ]
# /usr/bin/addlogo can only be executed after upstart of web, but no trigger available...
