#!/bin/bash
        
iptables -N EXT-TRAFFIC | iptables -F EXT-TRAFFIC
iptables -A INPUT -i eth0 -j EXT-TRAFFIC
ip6tables -N EXT-TRAFFIC | ip6tables -F EXT-TRAFFIC
ip6tables -A INPUT -i eth0 -j EXT-TRAFFIC
       
iptables -A EXT-TRAFFIC -m state --state ESTABLISHED -j ACCEPT
iptables -A EXT-TRAFFIC -p icmp -j ACCEPT
iptables -A EXT-TRAFFIC -p tcp -m tcp --dport 22 -j ACCEPT
iptables -A EXT-TRAFFIC -p tcp -m tcp --dport 80 -j ACCEPT
iptables -A EXT-TRAFFIC -p tcp -m tcp --dport 443 -j ACCEPT
iptables -A EXT-TRAFFIC -p tcp -m tcp --dport 4443 -j ACCEPT
iptables -A EXT-TRAFFIC -p udp -m udp --dport 10000 -j ACCEPT
iptables -A EXT-TRAFFIC -j REJECT
       
ip6tables -A EXT-TRAFFIC -m state --state ESTABLISHED -j ACCEPT
ip6tables -A EXT-TRAFFIC -p icmpv6 -j ACCEPT
ip6tables -A EXT-TRAFFIC -p tcp -m tcp --dport 22 -j ACCEPT
ip6tables -A EXT-TRAFFIC -p tcp -m tcp --dport 80 -j ACCEPT
ip6tables -A EXT-TRAFFIC -p tcp -m tcp --dport 443 -j ACCEPT
ip6tables -A EXT-TRAFFIC -p tcp -m tcp --dport 4443 -j ACCEPT
ip6tables -A EXT-TRAFFIC -p udp -m udp --dport 10000 -j ACCEPT
ip6tables -A EXT-TRAFFIC -j REJECT
